sudo: required
services:
  - docker
language: python
python:
  - 3.6.0
before_install:
  - make pull
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make build
  - make run
  - make test
  - make travis-coverage
after_script:
  - cd api/src
  - ../../cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
