web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - api:api
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: ./wait-for-it.sh api:8000 -- /usr/local/bin/gunicorn -w 2 -b :8000 app:app

api:
  restart: always
  build: ./api
  expose:
    - "8000"
  links:
    - postgres:postgres
  env_file: .env
  command: ./wait-for-it.sh postgres:5432 -- /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
    - api
  links:
    - web:web
    - api:api
  command: ./wait-for-it.sh web:8000

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432"
